### ISSUE TITLE
Activation de Turnstile sur le formulaire de mot de passe oublié

### ISSUE THREAD

**Issue by valentin-anamorphik** [Pixel-Open/prestashop-cloudflare-turnstile#3]
Bonjour,

Nous rencontrons un problème lorsque Turnstile est activé sur le formulaire de mot de passe oublié.

1. La demande de mot de passe oublié fonctionne.
2. Nous recevons l'email avec le lien
3. Nous cliquons sur le lien afin de renseigner notre nouveau de mot de passe
4. La soumission ne fonctionne pas, nous avons un message d'erreur indiquant que la sécurité n'a pas pu être vérifié

La fonctionnalité du mot de passe oubliée fonctionne à nouveau si nous désactivons Turnstile sur le formulaire de réinitialisation de mot de passe.

**Comment by matthieu2607** [comment]
Bonsoir @valentin-anamorphik,
Merci pour toutes ces précisions, nous allons déployer un fix prochainement.

**Comment by magentix** [comment]
Bonsoir @valentin-anamorphik,

Le problème a été reproduit sur Prestashop 1.7 et 8. Le contrôleur est partagé pour les 2 actions : envoi de l'e-mail et modification du mot de passe.

Un fix a été déployé. Pouvez-vous mettre à jour le module vers la release 1.1.1 ?

Merci beaucoup,
Matthieu

**Comment by valentin-anamorphik** [comment]
Bonjour @matthieu2607, @magentix ,

Nous vous confirmons que le problème est résolu.

Merci à vous.
